### ISSUE TITLE
引入配置失败

### ISSUE THREAD

**Issue by lipangit** [chenenyu/img-optimizer-gradle-plugin#1]
报错是

Gradle **\* project refresh failed
Error:Cause: com/android/build/gradle/internal/model/DefaultAndroidProject:Unsupported major.minor version 52.0

**Comment by chenenyu** [comment]
请问你的JDK是什么版本呢

**Comment by lipangit** [comment]
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by lipangit** [comment]
major.minor 这是啥

**Comment by chenenyu** [comment]
http://www.jianshu.com/p/9c5fa04f41bb  目测是AS的jdk配置有问题  我的jdk跟你的版本是一样的，没有任何问题。

**Comment by lipangit** [comment]
完美

**Comment by chenenyu** [comment]
原来是JieCao的作者，失敬失敬~
