### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by wuzheng4android** [chenenyu/img-optimizer-gradle-plugin#10]
![image](https://user-images.githubusercontent.com/5113478/45794416-30ebac80-bcc9-11e8-9ac2-d0934a1ab536.png)
![image](https://user-images.githubusercontent.com/5113478/45794425-3a751480-bcc9-11e8-82ac-d4b83d716144.png)
大神求帮助

**Comment by chenenyu** [comment]
版本号 1.1.1
