### ISSUE TITLE
img-optimizer在gradle 6.1.1版本里报错

### ISSUE THREAD

**Issue by Ezreal147** [chenenyu/img-optimizer-gradle-plugin#11]
我把android studio更新到了4.0，而gradle最低版本要求为6.1.1，在sync build.gradle时报错，提示
`Gradle sync failed: Unnecessarily replacing a task that does not exist is not supported.  Use create() or register() directly instead.  You attempted to replace a task named 'optimizeAppDebug', but there is no existing task with that name`
当我注释掉`apply plugin: 'img-optimizer'`后，项目能够正常编译。

**Comment by chenenyu** [comment]
感谢反馈，下周看看

**Comment by chenenyu** [comment]
try `1.2.0`

**Comment by Ezreal147** [comment]
好的谢谢
