### ISSUE TITLE
'imgDirs' is missing 

### ISSUE THREAD

**Issue by zhangxu2814** [chenenyu/img-optimizer-gradle-plugin#12]
Some problems were found with the configuration of task ':app:optimizeRelease' (type 'ImgOptimizerTask').
  - Type 'com.chenenyu.imgoptimizer.task.ImgOptimizerTask' property 'imgDirs' is missing an input or output annotation.

gradle:7.0.4

**Comment by chenenyu** [comment]
请问是使用的 `agp` 7.0+ 和 java sdk 11 吗？

**Comment by chenenyu** [comment]
try 1.3.0

**Comment by zhangxu2814** [comment]
点个赞，这速度真快
