### ISSUE TITLE
日志显示error

### ISSUE THREAD

**Issue by ggggxiaolong** [chenenyu/img-optimizer-gradle-plugin#3]
## 2016-07-11 09:20:52  error: Failed! /(项目地址)/app/src/main/res/mipmap-xhdpi/play_ptz_disabel.png

2016-07-11 09:20:52  error: Exit: 2. /(项目地址)/app/build/pngquant/pngquant: 1: /(项目地址)/app/build/pngquant/pngquant: �����H: not found/(项目地址)/app/build/pngquant/pngquant: 2: /(项目地址)/app/build/pngquant/pngquant: Syntax error: "(" unexpec

**Comment by chenenyu** [comment]
每个都失败吗？日志都是这个？   请问是什么操作系统呢？

**Comment by ggggxiaolong** [comment]
是的  全部失败了，操作系统是ubuntu 16.04

**Comment by chenenyu** [comment]
手里目前只有macOS和windows，猜测是因为权限问题，可以尝试给项目的根文件夹可执行权限，例如 `chmod +x file`，我想办法找个ubuntu的机器测试下。

**Comment by ggggxiaolong** [comment]
应该还是/(项目地址)/app/build/pngquant/pngquant  这个文件的问题，这个文件是有执行权限的，但是运行会报错{bash: ./pngquant: cannot execute binary file: Exec format error}，然后我把项目（pngquant）download下来make然后把生成pngquant的文件覆盖项目下的pngquant。再次执行gradle的压缩任务就会生成压缩的图片。

**Comment by chenenyu** [comment]
感谢反馈。按道理说mac版本的bin在linux上是没问题的。。。

**Comment by chenenyu** [comment]
最新版[`1.1.0`](https://github.com/chenenyu/img-optimizer-gradle-plugin/releases/tag/1.1.0)已增加对Ubuntu的支持，欢迎测试使用。
