### ISSUE TITLE
groovy项目如何debug

### ISSUE THREAD

**Issue by neuyu** [chenenyu/img-optimizer-gradle-plugin#4]
可能在这儿问这个问题不合适，但是还是很想知道作者如何debug

**Comment by chenenyu** [comment]
这是个好问题。。。 总结下来就是不要轻易进groovy的坑。  debug的麻烦程度简直令人发指，我基本上就是打印log，然后打包成maven项目，然后在demo中引用maven项目。所以，每一个变量的变动就要重复这个复杂的过程。

**Comment by chenenyu** [comment]
写代码可能只需要1分钟，但是如果出了问题，可能要花半天时间排查 - -！
star一下呗~

**Comment by neuyu** [comment]
@chenenyu 写过groovy的插件，debug确实是个问题，以为楼主会有相关的解决方案

**Comment by neuyu** [comment]
@chenenyu 已经follow

**Comment by chenenyu** [comment]
3q，如果你有更好的解决方案，请告知于我。 ^ ^
