### ISSUE TITLE
triggerSize 怎么用

### ISSUE THREAD

**Issue by lipangit** [chenenyu/img-optimizer-gradle-plugin#7]
你好triggerSize的数值如何计算，怎么来的，建议设成多少，多谢

**Comment by chenenyu** [comment]
triggerSize 是触发优化的阈值，假如你不想优化小图片，比如2kb以下的图片忽略掉 ，就可以设置为2，默认是优化所有图片的。

**Comment by beilly** [comment]
建议是加上单位说明,我是看了这个才知道单位是k
